# DO LOGIN #
POST http://localhost:6000/session  HTTP/1.1
content-type: application/json

{
    "username": "mattiapapa"
}


###

# SET USERNAME #
PUT http://localhost:6000/profiles/3/username HTTP/1.1
Authorization: 3
content-type: application/json

{
    "username": "cizzo"
}

### 

# DELETE USER #
DELETE http://localhost:6000/profiles/5  HTTP/1.1
Authorization: 5

###

# CREATE GROUP #
POST http://localhost:6000/profiles/1/groups  HTTP/1.1
Authorization: 1
content-type: application/json

{
    "groupName": "provaGruppo1",
    "users" : [
        {
            "username": "lachi"
        },
        {
            "username": "mattiapapa"
        }
    ]
}

### 

# ADD TO GROUP #
PUT http://localhost:6000/profiles/1/groups/1  HTTP/1.1
Authorization: 1
content-type: application/json 

{
    "users" : [
        {
            "username": "erosito"
        },
        {
            "username": "cizzo"
        }
    ]
}

### 

# LEAVE GROUP #
DELETE http://localhost:6000/profiles/1/groups/1  HTTP/1.1
Authorization: 1

###

# SET GROUPNAME #
PUT http://localhost:6000/profiles/1/groups/1/name HTTP/1.1
Authorization: 1
content-type: application/json

{
    "groupName": "negletti"
}